### ISSUE TITLE
Does not respect the initial rotation of the box object lattice for the volume form

### ISSUE THREAD

**Issue by SbstnDC** [BenjaminSauder/SimpleLattice#12]
Hello, people.

The new version 0.1.6 in blender 3.5.1, does not respect the initial rotation of the box object lattice! I attach pictures.

![image](https://github.com/BenjaminSauder/SimpleLattice/assets/22725270/0bbb6f2e-039b-4b54-ac71-857630108337)

I'm manually doing altR to fix it

**Comment by EugeneDudavkin** [comment]
What orientation method do you use? It seems you are using "Normal" method, instead of "Local" or other
![SL_orientation](https://github.com/BenjaminSauder/SimpleLattice/assets/87300864/9fd8137e-c9b1-4222-bc72-95ebc470259d)

also you can tweak angles in undo panel while creating simple lattice object
![Tweak_Angles_0_1_6](https://github.com/BenjaminSauder/SimpleLattice/assets/87300864/3cd933ec-1eac-4f9b-831f-963d0b3bbf80)
